#################################################################PROD##############################################################################

server.port = 8080
server.contextPath=/anuppur/
security.basic.enabled=false
server.session.timeout=1800
spring.main.banner-mode=off

#server.servlet.session.timeout=30m
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.http-only=true

#Sumit for L1
security.enable-csrf=false

#spring.jpa.properties.hibernate.show_sql=false
#spring.jpa.properties.hibernate.format_sql=true

# MySql settings
#spring.datasource.url=jdbc:mysql://10.115.196.19:3306/mlalads_db?createDatabaseIfNotExist=true&useSSL=false&useEncoding=true&characterEncoding=UTF-8&noAccessToProcedureBodies=true
#spring.datasource.url=jdbc:mysql://10.115.96.111:3306/dhs?createDatabaseIfNotExist=true&useSSL=false&useEncoding=true&characterEncoding=UTF-8&jdbcCompliantTruncation=false
#Latest DB 
#spring.datasource.url=jdbc:mysql://10.115.96.100:3306/dhs_staging_05oct23?createDatabaseIfNotExist=true&useSSL=false&useEncoding=true&characterEncoding=UTF-8&jdbcCompliantTruncation=false
#spring.datasource.url=jdbc:mysql://10.115.96.100:3306/dhs_07feb2024?createDatabaseIfNotExist=true&useSSL=false&useEncoding=true&characterEncoding=UTF-8&jdbcCompliantTruncation=false
#spring.datasource.url=jdbc:mysql://localhost:3306/dhs_07feb2024?createDatabaseIfNotExist=true&useSSL=false&useEncoding=true&characterEncoding=UTF-8
spring.datasource.url=jdbc:mysql://10.115.196.19:3306/dhs_anuppur?createDatabaseIfNotExist=true&useSSL=false&useEncoding=true&characterEncoding=UTF-8
#spring.datasource.url=jdbc:mysql://10.115.253.116:3306/mlalads_db?createDatabaseIfNotExist=true&useSSL=false&useEncoding=true&characterEncoding=UTF-8
spring.datasource.username=dhs_user
#spring.datasource.username=dms_usr
#spring.datasource.password=Dm$0dm$@321
#spring.datasource.password=D@*s@h12345
spring.datasource.password=D@h*s*1234
#spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.jdbc.Driver




# === Connection Pool Settings (Increased Limits) ===
spring.datasource.tomcat.max-active=150
spring.datasource.tomcat.max-wait=20000
spring.datasource.tomcat.min-idle=20
spring.datasource.tomcat.max-idle=75
spring.datasource.tomcat.test-on-borrow=true
spring.datasource.tomcat.validation-query=SELECT 1

# Number of ms to wait before throwing an exception if no connection is available.
#spring.datasource.tomcat.max-wait=10000
 
# Maximum number of active connections that can be allocated from this pool at the same time.
#spring.datasource.tomcat.max-active=50

# Validate the connection before borrowing it from the pool.
#spring.datasource.tomcat.test-on-borrow=true

logging.level.org.springframework.web=ERROR
logging.level.com.dms=INFO

# Logging pattern for the console
logging.pattern.console= %d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Logging pattern for file
logging.pattern.file= %d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n


#logging.file=D:/logs/dhs_wms.log
#logging.file=/opt/DHS_WMS/dhs_wms_applog/anuppur.log
logging.file=/opt/ANUPPUR_WMS/anuppur_wms_applog/anuppur.log


#mail.smtp.host=mail.mp.gov.in
#mail.smtp.port=465
#mail.from=Admin
#mail.username=
#mail.password=



#change it for Production environment
#mail.smtp.host=email.gov.in
#mail.smtp.port=465
#mail.from=DHS
#mail.username=noreply.mphealth-cwts.mp.gov.in
#mail.password=Noreply@1234

#sms.userName=DITMP-COMDES
#sms.password=COMDES#1234
#sms.senderId=COMDES
#sms.url=https://msdgweb.mgov.gov.in/esms/sendsmsrequest

#sms.secureKey=4394f37b-cf49-479e-850c-9b67ec57f1fa
#sms.url=https://msdgweb.mgov.gov.in/esms/sendsmsrequestDLT
#sms.userName=DITMP-MPNRHM
#sms.password=mpnrhm@2013
#sms.senderId=MPNRHM


#cdac.sms.userName=DITMP-MPNRHM
#cdac.sms.password=mpnrhm@2013
#cdac.sms.senderId=MPNRHM

#cdac.sms.url=https://msdgweb.mgov.gov.in/esms/sendsmsrequestDLT

#cdac.sms.secureKey=4394f37b-cf49-479e-850c-9b67ec57f1fa


#document.root=D:/DHS/dhs_docs/
#document.root=/opt/DHS_WMS/dhs_wms_docs/
document.root=/opt/ANUPPUR_WMS/anuppur_wms_docs/
#document.citizen=D:/DHS/dhs_citizen/
#document.citizen=/opt/DHS_WMS/dhs_citizen/
document.citizen=/opt/ANUPPUR_WMS/anuppur_citizen/

document.work=WORK_DOCS/
document.technical=WORK/TECH_DOC/
document.administrator=WORK/ADMS_DOC/
document.tsRevised=WORK/TECH_DOC/REVISED_TS/
document.asRevised=WORK/ADMS_DOC/REVISED_AS/
document.tender=WORK/TENDER_DOC/
document.workprogress=WORK/WORK_PROGRESS/
document.drawingfile=WORK/WORK_DRAWING/
document.cc=WORK/CC_DOC/
document.dmAttachment=WORK/DMAttachement/
host.ip.address = www.anuppur-wms.mp.gov.in

stagepassing.imageUrl = www.anuppur-wms.mp.gov.in

applicationDeploymentServerName=www.anuppur-wms.mp.gov.in

spring.http.multipart.max-file-size=25MB
spring.http.multipart.max-request-size=25MB
server.tomcat.max-http-post-size=6291456

spring.devtools.restart.enabled=true

spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true