//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.30 at 08:11:05 PM IST 
//


package com.anuppur.template;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="page1">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="district" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="block" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="gramPanchayat" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="village" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="parliamentaryConstituency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="legislativeConstituency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="workNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="workName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="workType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="year" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="scheme" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="workPriority" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="workHead" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="implementationAgency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="subEngineerName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="estimatedAmount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="amountReleased" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="performanceGrant" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="tsDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="tsNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="asDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="asNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="page2">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="stage3Pic1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="stage3Pic2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="stage3Pic3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="stage3Pic4" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="meta">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="instanceID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "page1",
    "page2",
    "meta"
})
@XmlRootElement(name = "Development_Monitoring_Legacy_Work")
public class DevelopmentMonitoringLegacyWork {

    @XmlElement(required = true)
    protected DevelopmentMonitoringLegacyWork.Page1 page1;
    @XmlElement(required = true)
    protected DevelopmentMonitoringLegacyWork.Page2 page2;
    @XmlElement(required = true)
    protected DevelopmentMonitoringLegacyWork.Meta meta;
    @XmlAttribute(name = "id")
    protected String id;

    /**
     * Gets the value of the page1 property.
     * 
     * @return
     *     possible object is
     *     {@link DevelopmentMonitoringLegacyWork.Page1 }
     *     
     */
    public DevelopmentMonitoringLegacyWork.Page1 getPage1() {
        return page1;
    }

    /**
     * Sets the value of the page1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link DevelopmentMonitoringLegacyWork.Page1 }
     *     
     */
    public void setPage1(DevelopmentMonitoringLegacyWork.Page1 value) {
        this.page1 = value;
    }

    /**
     * Gets the value of the page2 property.
     * 
     * @return
     *     possible object is
     *     {@link DevelopmentMonitoringLegacyWork.Page2 }
     *     
     */
    public DevelopmentMonitoringLegacyWork.Page2 getPage2() {
        return page2;
    }

    /**
     * Sets the value of the page2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link DevelopmentMonitoringLegacyWork.Page2 }
     *     
     */
    public void setPage2(DevelopmentMonitoringLegacyWork.Page2 value) {
        this.page2 = value;
    }

    /**
     * Gets the value of the meta property.
     * 
     * @return
     *     possible object is
     *     {@link DevelopmentMonitoringLegacyWork.Meta }
     *     
     */
    public DevelopmentMonitoringLegacyWork.Meta getMeta() {
        return meta;
    }

    /**
     * Sets the value of the meta property.
     * 
     * @param value
     *     allowed object is
     *     {@link DevelopmentMonitoringLegacyWork.Meta }
     *     
     */
    public void setMeta(DevelopmentMonitoringLegacyWork.Meta value) {
        this.meta = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="instanceID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "instanceID"
    })
    public static class Meta {

        @XmlElement(required = true)
        protected String instanceID;

        /**
         * Gets the value of the instanceID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInstanceID() {
            return instanceID;
        }

        /**
         * Sets the value of the instanceID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInstanceID(String value) {
            this.instanceID = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="district" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="block" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="gramPanchayat" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="village" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="parliamentaryConstituency" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="legislativeConstituency" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="workNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="workName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="workType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="year" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="scheme" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="workPriority" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="workHead" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="implementationAgency" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="subEngineerName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="estimatedAmount" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="amountReleased" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="performanceGrant" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="tsDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="tsNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="asDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="asNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "district",
        "block",
        "gramPanchayat",
        "village",
        "parliamentaryConstituency",
        "legislativeConstituency",
        "workNo",
        "workName",
        "workType",
        "year",
        "scheme",
        "workPriority",
        "workHead",
        "implementationAgency",
        "subEngineerName",
        "estimatedAmount",
        "amountReleased",
        "performanceGrant",
        "tsDate",
        "tsNo",
        "asDate",
        "asNo",
        "status"
    })
    public static class Page1 {

        @XmlElement(required = true)
        protected String district;
        @XmlElement(required = true)
        protected String block;
        @XmlElement(required = true)
        protected String gramPanchayat;
        @XmlElement(required = true)
        protected String village;
        @XmlElement(required = true)
        protected String parliamentaryConstituency;
        @XmlElement(required = true)
        protected String legislativeConstituency;
        @XmlElement(required = true)
        protected String workNo;
        @XmlElement(required = true)
        protected String workName;
        @XmlElement(required = true)
        protected String workType;
        @XmlElement(required = true)
        protected Long year;
        @XmlElement(required = true)
        protected String scheme;
        @XmlElement(required = true)
        protected String workPriority;
        @XmlElement(required = true)
        protected String workHead;
        @XmlElement(required = true)
        protected Long implementationAgency;
        @XmlElement(required = true)
        protected String subEngineerName;
        @XmlElement(required = true)
        protected String estimatedAmount;
        @XmlElement(required = true)
        protected String amountReleased;
        @XmlElement(required = true)
        protected String performanceGrant;
        @XmlElement(required = true)
        protected String tsDate;
        @XmlElement(required = true)
        protected String tsNo;
        @XmlElement(required = true)
        protected String asDate;
        @XmlElement(required = true)
        protected String asNo;
        @XmlElement(required = true)
        protected String status;

        /**
         * Gets the value of the district property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDistrict() {
            return district;
        }

        /**
         * Sets the value of the district property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDistrict(String value) {
            this.district = value;
        }

        /**
         * Gets the value of the block property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBlock() {
            return block;
        }

        /**
         * Sets the value of the block property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBlock(String value) {
            this.block = value;
        }

        /**
         * Gets the value of the gramPanchayat property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGramPanchayat() {
            return gramPanchayat;
        }

        /**
         * Sets the value of the gramPanchayat property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGramPanchayat(String value) {
            this.gramPanchayat = value;
        }

        /**
         * Gets the value of the village property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVillage() {
            return village;
        }

        /**
         * Sets the value of the village property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVillage(String value) {
            this.village = value;
        }

        /**
         * Gets the value of the parliamentaryConstituency property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getParliamentaryConstituency() {
            return parliamentaryConstituency;
        }

        /**
         * Sets the value of the parliamentaryConstituency property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setParliamentaryConstituency(String value) {
            this.parliamentaryConstituency = value;
        }

        /**
         * Gets the value of the legislativeConstituency property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLegislativeConstituency() {
            return legislativeConstituency;
        }

        /**
         * Sets the value of the legislativeConstituency property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLegislativeConstituency(String value) {
            this.legislativeConstituency = value;
        }

        /**
         * Gets the value of the workNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWorkNo() {
            return workNo;
        }

        /**
         * Sets the value of the workNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWorkNo(String value) {
            this.workNo = value;
        }

        /**
         * Gets the value of the workName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWorkName() {
            return workName;
        }

        /**
         * Sets the value of the workName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWorkName(String value) {
            this.workName = value;
        }

        /**
         * Gets the value of the workType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWorkType() {
            return workType;
        }

        /**
         * Sets the value of the workType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWorkType(String value) {
            this.workType = value;
        }

        /**
         * Gets the value of the year property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public Long getYear() {
            return year;
        }

        /**
         * Sets the value of the year property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setYear(Long value) {
            this.year = value;
        }

        /**
         * Gets the value of the scheme property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getScheme() {
            return scheme;
        }

        /**
         * Sets the value of the scheme property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setScheme(String value) {
            this.scheme = value;
        }

        /**
         * Gets the value of the workPriority property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWorkPriority() {
            return workPriority;
        }

        /**
         * Sets the value of the workPriority property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWorkPriority(String value) {
            this.workPriority = value;
        }

        /**
         * Gets the value of the workHead property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWorkHead() {
            return workHead;
        }

        /**
         * Sets the value of the workHead property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWorkHead(String value) {
            this.workHead = value;
        }

        /**
         * Gets the value of the implementationAgency property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public Long getImplementationAgency() {
            return implementationAgency;
        }

        /**
         * Sets the value of the implementationAgency property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setImplementationAgency(Long value) {
            this.implementationAgency = value;
        }

        /**
         * Gets the value of the subEngineerName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSubEngineerName() {
            return subEngineerName;
        }

        /**
         * Sets the value of the subEngineerName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSubEngineerName(String value) {
            this.subEngineerName = value;
        }

        /**
         * Gets the value of the estimatedAmount property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEstimatedAmount() {
            return estimatedAmount;
        }

        /**
         * Sets the value of the estimatedAmount property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEstimatedAmount(String value) {
            this.estimatedAmount = value;
        }

        /**
         * Gets the value of the amountReleased property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAmountReleased() {
            return amountReleased;
        }

        /**
         * Sets the value of the amountReleased property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAmountReleased(String value) {
            this.amountReleased = value;
        }

        /**
         * Gets the value of the performanceGrant property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPerformanceGrant() {
            return performanceGrant;
        }

        /**
         * Sets the value of the performanceGrant property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPerformanceGrant(String value) {
            this.performanceGrant = value;
        }

        /**
         * Gets the value of the tsDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTsDate() {
            return tsDate;
        }

        /**
         * Sets the value of the tsDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTsDate(String value) {
            this.tsDate = value;
        }

        /**
         * Gets the value of the tsNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTsNo() {
            return tsNo;
        }

        /**
         * Sets the value of the tsNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTsNo(String value) {
            this.tsNo = value;
        }

        /**
         * Gets the value of the asDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAsDate() {
            return asDate;
        }

        /**
         * Sets the value of the asDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAsDate(String value) {
            this.asDate = value;
        }

        /**
         * Gets the value of the asNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAsNo() {
            return asNo;
        }

        /**
         * Sets the value of the asNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAsNo(String value) {
            this.asNo = value;
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatus(String value) {
            this.status = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="stage3Pic1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="stage3Pic2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="stage3Pic3" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="stage3Pic4" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "stage3Pic1",
        "stage3Pic2",
        "stage3Pic3",
        "stage3Pic4"
    })
    public static class Page2 {

        @XmlElement(required = true)
        protected String stage3Pic1;
        @XmlElement(required = true)
        protected String stage3Pic2;
        @XmlElement(required = true)
        protected String stage3Pic3;
        @XmlElement(required = true)
        protected String stage3Pic4;

        /**
         * Gets the value of the stage3Pic1 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStage3Pic1() {
            return stage3Pic1;
        }

        /**
         * Sets the value of the stage3Pic1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStage3Pic1(String value) {
            this.stage3Pic1 = value;
        }

        /**
         * Gets the value of the stage3Pic2 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStage3Pic2() {
            return stage3Pic2;
        }

        /**
         * Sets the value of the stage3Pic2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStage3Pic2(String value) {
            this.stage3Pic2 = value;
        }

        /**
         * Gets the value of the stage3Pic3 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStage3Pic3() {
            return stage3Pic3;
        }

        /**
         * Sets the value of the stage3Pic3 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStage3Pic3(String value) {
            this.stage3Pic3 = value;
        }

        /**
         * Gets the value of the stage3Pic4 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStage3Pic4() {
            return stage3Pic4;
        }

        /**
         * Sets the value of the stage3Pic4 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStage3Pic4(String value) {
            this.stage3Pic4 = value;
        }

    }

}
