//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.30 at 08:11:05 PM IST 
//


package com.anuppur.template;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.dms.template package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactoryLegacyWork {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.dms.template
     * 
     */
    public ObjectFactoryLegacyWork() {
    }

    /**
     * Create an instance of {@link DevelopmentMonitoringLegacyWork }
     * 
     */
    public DevelopmentMonitoringLegacyWork createDevelopmentMonitoringLegacyWork() {
        return new DevelopmentMonitoringLegacyWork();
    }

    /**
     * Create an instance of {@link DevelopmentMonitoringLegacyWork.Page1 }
     * 
     */
    public DevelopmentMonitoringLegacyWork.Page1 createDevelopmentMonitoringLegacyWorkPage1() {
        return new DevelopmentMonitoringLegacyWork.Page1();
    }

    /**
     * Create an instance of {@link DevelopmentMonitoringLegacyWork.Page2 }
     * 
     */
    public DevelopmentMonitoringLegacyWork.Page2 createDevelopmentMonitoringLegacyWorkPage2() {
        return new DevelopmentMonitoringLegacyWork.Page2();
    }

    /**
     * Create an instance of {@link DevelopmentMonitoringLegacyWork.Meta }
     * 
     */
    public DevelopmentMonitoringLegacyWork.Meta createDevelopmentMonitoringLegacyWorkMeta() {
        return new DevelopmentMonitoringLegacyWork.Meta();
    }

}
